In [18]:
%matplotlib inline
import random
import numpy as np
import matplotlib.pyplot as plt

In [19]:
北七='9487'
北七[1:3] 

'48'

In [20]:
北七 = [8, 7]
94*北七

[8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7,
 8,
 7]

In [27]:
random(87,1)

TypeError: 'module' object is not callable

In [30]:
2 * np.array([13, 14, 55, 66])

array([ 26,  28, 110, 132])

In [58]:
A = [5, 5, 6, 6]

B = [1, 3, 1, 4]
A*B

TypeError: can't multiply sequence by non-int of type 'list'

In [49]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
def 北七():

    return '87'

In [56]:
北七()

'87'

In [57]:
seafood = '炎龍'

print('感恩{}，讚嘆{}'.format(seafood,seafood))

感恩炎龍，讚嘆炎龍


In [64]:
np.random.randint(5)

3

In [68]:
plt.plot[np.random.randn[87]]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [69]:
messenge = input('>>')

while messenge != '再見':

    print('很好，然後呢？')

    messenge = input('>>')

print('我們有緣再相見')

>>再見
我們有緣再相見


In [70]:
year = 1

l = [9,4,8,7]

for i in l:

    year = year*i

In [71]:
year

2016

In [73]:
'Z'>'B'

True

In [74]:
五五六六 = np.linspace(56,5566)

五五六六[五五六六<87]

array([56.])